This notebook uses the analytical solution to linear regression

$ \theta = (X^{T} X)^{-1} X^{T} y $

In [28]:
################################################
## Improve your linear regression with basis
## functions and regularization
##
##
################################################

import numpy as np

################################################

M_basis = 4            ## number of basis to use

lambd = 0.00001        ## regularization parameter




The following is the gaussian basis function



$ \large \phi _{i} (x) = e^{- \gamma_{i} \lVert \mu _{i} - x \rVert _{2} ^{2} }  $    


In [29]:
################################################
## np.linalg.norm    ->     norm

def gaussian_basis(x, mu, gamma=1):
    return np.exp(-gamma * np.linalg.norm(mu-x)**2)



The data

In [30]:
################################################
## data 

x = np.array(  [-1,   -0.8, -0.6, -0.4, -0.2,    0,  0.2, 0.4, 0.6, 0.8,   1]  )

t = np.array(  [-4.9, -3.5, -2.8,  0.8,  0.3, -1.6, -1.3, 0.5, 2.1, 2.9, 5.6]    )

################################################
## calculate matrix Phi

Phi = np.ones(   (t.shape[0], M_basis)   )
print(Phi.shape)

for m in range(M_basis-1):
    mu = m/M_basis
    Phi[:, m+1] = np.vectorize(gaussian_basis)(x, mu)
    
print(Phi)

    
################################################

(11, 4)
[[1.         0.36787944 0.20961139 0.10539922]
 [1.         0.52729242 0.33203995 0.18451952]
 [1.         0.69767633 0.4855369  0.29819728]
 [1.         0.85214379 0.65540625 0.44485807]
 [1.         0.96078944 0.81668648 0.61262639]
 [1.         1.         0.93941306 0.77880078]
 [1.         0.96078944 0.99750312 0.91393119]
 [1.         0.85214379 0.97775124 0.99004983]
 [1.         0.69767633 0.8847059  0.99004983]
 [1.         0.52729242 0.73896849 0.91393119]
 [1.         0.36787944 0.56978282 0.77880078]]


Normal Linear Regression


$ h(x, w) = w^T x $

    

Linear Regression with basis functions


$ h(x, w) = w_{0} \phi_{0}(x) + ... + w_{M-1} \phi_{M-1}(x) $ 


<br/>


$ h(x, w) = \sum \limits _{m=0} ^{M-1} w_{m} \phi_{m}(x)  $ 

<br/>

$ h(x, w) = w^T \phi (x) $


In [31]:
w = np.linalg.inv(Phi.T @ Phi) @ Phi.T @ t

print(w)

alpha = sum((t - Phi @ w)**2) / len(t)

print(alpha)

[ -18.08330188  125.73936387 -230.07785175  137.65059622]
0.9397171260456706


Linear regression with basis functions and normalization

<br/>


$ E(w) = \sum \limits _{i=1} ^{N} ( t_{n} - w^T \phi(x_i) )^2 + \lambda \sum \limits _{j=0} ^{M-1} | w_{j} | ^{q} $ 

<br/>

q can be 1 or 2 


In [32]:
w = np.linalg.inv(lambd * np.identity(M_basis) + Phi.T @ Phi) @ Phi.T @ t      ## added regularization parameter

print(w)

alpha = sum((t - Phi @ w)**2) / len(t)

print(alpha)

[ -17.52389644  121.36512632 -222.40282234  133.31883125]
0.9422854323201991
