In [1]:
#######################################################
##
## Linear Regression
##
## Ricardo A. Calix, Ph.D.
## www.rcalix.com
##
#######################################################

import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset, DataLoader

#######################################################

N_EPOCHS = 100
batch_size = 5

#######################################################
## model

def model(x):
    return x @ w.t() + b

#######################################################
## Mean Squared Error (MSE)

def mse( preds, targets):
    diff = targets - preds
    return torch.sum( diff * diff) / diff.numel()

#######################################################


def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss:', loss_fn(model(inputs), targets))
            



In [2]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)


print(x)
print(w)
print(b)

#######################################################

y = w*x + b

print(y)

#######################################################
## compute the derivative (e.g. the gradient)

y.backward()

print("dy/dw:", w.grad)
print("dy/db:", b.grad)

tensor(3.)
tensor(4., requires_grad=True)
tensor(5., requires_grad=True)
tensor(17., grad_fn=<AddBackward0>)
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [3]:



######################################################
## data for crop yields for apples and oranges


## features: temp, rainfall, and humidity

inputs  = np.array([[ 73,  67, 43],
                    [ 91,  88, 64],
                    [ 87, 134, 58],
                    [102,  43, 37],
                    [ 69,  96, 70],
                    [ 73,  67, 43],
                    [ 91,  88, 64],
                    [ 87, 134, 58],
                    [102,  43, 37],
                    [ 69,  96, 70],
                    [ 73,  67, 43],
                    [ 91,  88, 64],
                    [ 87, 134, 58],
                    [102,  43, 37],
                    [ 69,  96, 70]], dtype='float32')

## targets: apples, oranges

targets = np.array([[ 56,  70],
                    [ 81, 101],
                    [119, 133],
                    [ 22,  37],
                    [103, 119],
                    [ 56,  70],
                    [ 81, 101],
                    [119, 133],
                    [ 22,  37],
                    [103, 119],
                    [ 56,  70],
                    [ 81, 101],
                    [119, 133],
                    [ 22,  37],
                    [103, 119]], dtype='float32') 


print(inputs)
print(targets)





[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]
 [ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]
 [ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [4]:
#######################################################

inputs  = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)




tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
#######################################################
## weights and biases

## 2x3 because 3 targets and 3 features

w = torch.rand(2, 3, requires_grad=True)
b = torch.rand(2,    requires_grad=True)

print(w)
print(b)

#######################################################

preds = model(inputs)

print(preds)
print(targets)


#######################################################
## compute loss

loss = mse(preds, targets)
print(loss)

#######################################################
## derivatives

loss.backward()


print(w)
print(w.grad)
print(b)
print(b.grad)

#######################################################
## Torch needs to reset gradients to zero every iteration

w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)



tensor([[0.5103, 0.6687, 0.6974],
        [0.7205, 0.4596, 0.6904]], requires_grad=True)
tensor([0.4836, 0.1279], requires_grad=True)
tensor([[112.5325, 113.2062],
        [150.4079, 150.3252],
        [174.9442, 164.4437],
        [107.0976, 118.9282],
        [148.7153, 142.2929],
        [112.5325, 113.2062],
        [150.4079, 150.3252],
        [174.9442, 164.4437],
        [107.0976, 118.9282],
        [148.7153, 142.2929],
        [112.5325, 113.2062],
        [150.4079, 150.3252],
        [174.9442, 164.4437],
        [107.0976, 118.9282],
        [148.7153, 142.2929]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor(3301.7878, grad_fn=<DivBackward0>)
tensor([[0.5103, 0

In [6]:
######################################################

for i in range(N_EPOCHS):
    preds = model(inputs)
    loss  = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

        
#######################################################
## calculate loss after training

preds = model(inputs)
loss  = mse(preds, targets)
print(loss)

#######################################################

print(preds)
print(targets)




tensor(152.2202, grad_fn=<DivBackward0>)
tensor([[ 60.6937,  74.7536],
        [ 83.9896, 102.0274],
        [108.9675, 122.7269],
        [ 41.0649,  62.5620],
        [ 93.4544, 106.6151],
        [ 60.6937,  74.7536],
        [ 83.9896, 102.0274],
        [108.9675, 122.7269],
        [ 41.0649,  62.5620],
        [ 93.4544, 106.6151],
        [ 60.6937,  74.7536],
        [ 83.9896, 102.0274],
        [108.9675, 122.7269],
        [ 41.0649,  62.5620],
        [ 93.4544, 106.6151]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [7]:
#######################################################
## define dataset

train_ds = TensorDataset(inputs, targets)
print(  train_ds[0:3]  )




(tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]]))


In [8]:
## define dataloader

train_dl = DataLoader(train_ds, batch_size, shuffle=True)

print(    next(iter(train_dl))   )



[tensor([[ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]]), tensor([[103., 119.],
        [ 81., 101.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 22.,  37.]])]


In [9]:
## define model again using nn

model = nn.Linear(3, 2)    
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[-0.3418, -0.0273,  0.4819],
        [-0.1262,  0.5325, -0.1350]], requires_grad=True)
Parameter containing:
tensor([ 0.1139, -0.3624], requires_grad=True)


In [10]:
## define built in optimizer

opt = torch.optim.SGD(   model.parameters(),   lr=1e-5    )

In [11]:
loss_fn = F.mse_loss

loss = loss_fn(      model(inputs), targets        )
print(loss)

tensor(6004.4604, grad_fn=<MseLossBackward0>)


In [12]:
fit(N_EPOCHS, model, loss_fn, opt)

preds = model(inputs)
print(preds)
print(targets)


Training loss: tensor(25.8325, grad_fn=<MseLossBackward0>)
tensor([[ 57.9844,  71.1952],
        [ 83.5237,  96.3827],
        [115.2624, 140.9801],
        [ 25.1092,  42.2642],
        [101.8197, 108.5670],
        [ 57.9844,  71.1952],
        [ 83.5237,  96.3827],
        [115.2624, 140.9801],
        [ 25.1092,  42.2642],
        [101.8197, 108.5670],
        [ 57.9844,  71.1952],
        [ 83.5237,  96.3827],
        [115.2624, 140.9801],
        [ 25.1092,  42.2642],
        [101.8197, 108.5670]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:


#######################################################

class SimpleNet(nn.Module):
    ## initialize the layers
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(3, 3)
        self.act1    = nn.ReLU()
        self.linear2 = nn.Linear(3, 2)
    
    ## perform inference
    def forward(self, x):
        x = self.linear1(x)
        x = self.act1(x)
        x = self.linear2(x)
        return x
    
#############################################################

model = SimpleNet()
opt = torch.optim.SGD(   model.parameters(), lr=1e-5   )
loss_fn = F.mse_loss

In [14]:
fit(1000, model, loss_fn, opt)

preds = model(inputs)
print(preds)
print(targets)


Training loss: tensor(0.6189, grad_fn=<MseLossBackward0>)
tensor([[ 57.2850,  70.3377],
        [ 81.9722, 100.8336],
        [119.2455, 132.5583],
        [ 21.2278,  36.9103],
        [101.4828, 119.5375],
        [ 57.2850,  70.3377],
        [ 81.9722, 100.8336],
        [119.2455, 132.5583],
        [ 21.2278,  36.9103],
        [101.4828, 119.5375],
        [ 57.2850,  70.3377],
        [ 81.9722, 100.8336],
        [119.2455, 132.5583],
        [ 21.2278,  36.9103],
        [101.4828, 119.5375]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
