## Sensitivity Analysis

Calculate partial derivatives of the function with respect to the independent variables. 

In [19]:
import torch



In [20]:

## x1 = torch.randn(100, requires_grad=True)

x1 = torch.randn(1, requires_grad=True)

x2 = torch.randn(1, requires_grad=True)



## u = u(x1,x2)

u = 3 * x1 ** 3 - x2 ** 2


print(u)



tensor([-0.2450], grad_fn=<SubBackward0>)


In [21]:

# 1st derivatives

dx1 = torch.autograd.grad(u, x1)[0]
dx2 = torch.autograd.grad(u, x2)[0]

print(dx1)
print(dx2)



tensor([0.9112])
tensor([1.1689])


In [22]:
'''

# 2nd derivatives (higher orders require `create_graph=True`)

dx2 = torch.autograd.grad(u, x, create_graph=True)[0]

ddx = torch.autograd.grad(dx, x)[0]

'''

'\n\n# 2nd derivatives (higher orders require `create_graph=True`)\n\ndx2 = torch.autograd.grad(u, x, create_graph=True)[0]\n\nddx = torch.autograd.grad(dx, x)[0]\n\n'